# Written by Steamify: Valve's cros_ec_cec, which knows the Steam Machine.
PACKAGE_NAME="@NAME@"
PACKAGE_VERSION="@VERSION@"
BUILT_MODULE_NAME[0]="cros-ec-cec"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
